window.UTTERAN_I18N = {
  ja: {
    navWorkspace: "文字起こし", navSettings: "設定", localOnly: "ローカル実行",
    workspaceEyebrow: "TRANSCRIPTION WORKSPACE", workspaceTitle: "文字起こしを開始",
    workspaceLead: "この環境で実際に利用できる構成だけを表示します。", refresh: "再検出",
    hardware: "ハードウェア", profile: "プロファイル", models: "導入済みモデル", nativeBuild: "ネイティブ構成",
    sourceOutput: "入力と出力", dropHint: "ファイルをウィンドウへドロップできます", inputPath: "入力ファイル／フォルダ", outputDir: "出力先", recursive: "サブフォルダも処理", includePatterns: "対象glob（カンマ区切り）", excludePatterns: "除外glob（カンマ区切り）",
    runtime: "実行環境", asrBackend: "ASRバックエンド", asrModel: "ASRモデル", asrDevice: "ASRデバイス", language: "言語", resume: "レジューム",
    resumeReuse: "再利用する", resumeFresh: "キャッシュを使わない", resumeForce: "全段階を再実行",
    diarization: "話者分離", enabled: "有効", diarBackend: "バックエンド", diarModel: "モデル", diarDevice: "デバイス", speakerMode: "話者数", automatic: "自動", fixed: "固定", range: "範囲", speakerCount: "人数", minimum: "最小", maximum: "最大",
    outputFormats: "出力形式", start: "文字起こしを開始", inProgress: "IN PROGRESS", processing: "処理しています", cancel: "キャンセル", elapsed: "経過", remaining: "残り目安", stalled: "しばらく進捗イベントがありません。処理は継続中です。", details: "詳細ログ", complete: "完了しました", openFolder: "出力フォルダを開く",
    settingsTitle: "設定", settingsLead: "GUI専用の設定です。CLIのconfig.tomlとは分離して保存します。", theme: "テーマ", dark: "ダーク", light: "ライト", displayLanguage: "表示言語", defaultProfile: "既定プロファイル", defaultInput: "既定入力先", defaultOutput: "既定出力先", tokenPrivacy: "保存済みの値は表示しません", saveToken: "トークンを保存", clear: "削除", privacyTitle: "プライバシー", privacyBody: "入力ファイルの履歴は保存しません。ファイル名に個人情報が含まれる可能性があるためです。", saveSettings: "設定を保存",
    noProfiles: "利用できるプロファイルがありません。setup.ps1 -Profile cuda などで環境を構築してください。", noRuntime: "このプロファイルには利用可能なASRモデルとデバイスの組み合わせがありません。モデル管理とデバイス診断を確認してください。", detecting: "環境を確認しています…", ready: "実行できます", saved: "保存しました", tokenSet: "設定済み", tokenUnset: "未設定", cancelled: "中断しました", failed: "処理に失敗しました", partial: "一部のファイルが失敗しました。詳細ログを確認してください。",
    guide_configuration: "設定値を確認し、利用可能な選択肢からやり直してください。", guide_dependency: "必要な依存関係、ffmpeg、モデルの導入状態を確認してください。", guide_input: "入力パスと、ffmpegで読み取れるファイルかを確認してください。", guide_model: "モデル管理から、選択したバックエンド用モデルを取得してください。", guide_token: "設定画面でHugging Faceトークンを保存し、モデル利用条件への同意を確認してください。", guide_memory: "GPUメモリ予算を超えました。話者分離など負荷の高い処理をCPUへ切り替えてください。", guide_ffmpeg: "setup.ps1を実行するか、CLI設定でffmpegのパスを指定してください。", guide_general: "詳細ログを確認し、同じ操作をCLIで再現して診断してください。", guide_cancelled: "処理ツリーを終了しました。レジュームして再開できます。", guide_partial: "成功した出力は保持されています。失敗したファイルを詳細ログで確認してください。"
  },
  en: {
    navWorkspace: "Transcribe", navSettings: "Settings", localOnly: "Local only",
    workspaceEyebrow: "TRANSCRIPTION WORKSPACE", workspaceTitle: "Start transcription", workspaceLead: "Only combinations detected as usable in this environment are shown.", refresh: "Detect again",
    hardware: "Hardware", profile: "Profile", models: "Installed models", nativeBuild: "Native variants", sourceOutput: "Input and output", dropHint: "You can drop a file onto this window", inputPath: "Input file or folder", outputDir: "Output folder", recursive: "Include subfolders", includePatterns: "Include globs (comma-separated)", excludePatterns: "Exclude globs (comma-separated)",
    runtime: "Runtime", asrBackend: "ASR backend", asrModel: "ASR model", asrDevice: "ASR device", language: "Language", resume: "Resume", resumeReuse: "Reuse completed stages", resumeFresh: "Do not use cache", resumeForce: "Run every stage again",
    diarization: "Speaker diarization", enabled: "Enabled", diarBackend: "Backend", diarModel: "Model", diarDevice: "Device", speakerMode: "Speaker count", automatic: "Automatic", fixed: "Fixed", range: "Range", speakerCount: "Count", minimum: "Minimum", maximum: "Maximum", outputFormats: "Output formats", start: "Start transcription",
    inProgress: "IN PROGRESS", processing: "Processing", cancel: "Cancel", elapsed: "Elapsed", remaining: "Estimated left", stalled: "No progress event has arrived recently. Processing may still be active.", details: "Detailed log", complete: "Completed", openFolder: "Open output folder",
    settingsTitle: "Settings", settingsLead: "GUI preferences are stored separately from CLI config.toml.", theme: "Theme", dark: "Dark", light: "Light", displayLanguage: "Display language", defaultProfile: "Default profile", defaultInput: "Default input folder", defaultOutput: "Default output folder", tokenPrivacy: "The stored value is never displayed", saveToken: "Save token", clear: "Remove", privacyTitle: "Privacy", privacyBody: "Input history is not saved because file names can contain personal information.", saveSettings: "Save settings",
    noProfiles: "No profile is available. Build one with setup.ps1 -Profile cuda or another suitable profile.", noRuntime: "This profile has no usable ASR model and device combination. Check model management and device diagnostics.", detecting: "Detecting environment…", ready: "Ready", saved: "Saved", tokenSet: "Configured", tokenUnset: "Not configured", cancelled: "Cancelled", failed: "Processing failed", partial: "Some files failed. Review the detailed log.",
    guide_configuration: "Review the settings and choose from currently available options.", guide_dependency: "Check required dependencies, ffmpeg, and installed models.", guide_input: "Check the input path and whether ffmpeg can decode the file.", guide_model: "Download the selected backend's model using model management.", guide_token: "Save a Hugging Face token in Settings and accept the model terms.", guide_memory: "The GPU memory budget was exceeded. Move high-load work such as diarization to CPU.", guide_ffmpeg: "Run setup.ps1 or configure the ffmpeg path in the CLI.", guide_general: "Review the detailed log and reproduce the command in the CLI for diagnosis.", guide_cancelled: "The process tree was terminated. You can resume the job later.", guide_partial: "Successful outputs were retained. Review the log for failed files."
  }
};
